version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Setup environment
          command: ./.circleci/setup.sh
      - run:
          name: Compute checksums
          command: ./.circleci/checksum-deps.sh
      - restore_cache:
          key: jars-{{ checksum "checksums.txt" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "checksums.txt" }}
      - run:
          name: Run tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
